In [5]:
import numpy as np
x=[3,10,5]
y=[4,6,9]
print(x,y)
print("greater than")
print(np.greater(x,y))
print("greater than or equal")
print(np.greater_equal(x,y))
print("less than")
print(np.less(x,y))
print("less than or equal")
print(np.less_equal(x,y))

[3, 10, 5] [4, 6, 9]
greater than
[False  True False]
greater equal
[False  True False]
less than
[ True False  True]
greater equal than
[ True False  True]


In [6]:
even=[x for x in range(30,70) if x%2==0]
print(even)

[30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68]


In [9]:
i=np.identity(3,dtype='int64')
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [18]:
n=np.arange(0,21)
n[(n>=9) & (n<=15)]*=-1
n

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [20]:
i=np.identity(5,dtype='int64')
np.fill_diagonal(i,[1,2,3,4,5])
print(i)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
a=np.matrix('1,2,3;4,5,6;7,8,9')
print(a)
print("total sum: ",np.sum(a))
print("column sum: ",np.sum(a,axis=0))
print("row sum: ",np.sum(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
total sum:  45
column sum:  [[12 15 18]]
row sum:  [[ 6]
 [15]
 [24]]


In [33]:
a=np.matrix('1,2,3;4,5,6;7,8,9')
a=np.array(a)
print(a)
file=open("text.txt","w")
c=str(a)
file.write(c)
file.close()
file=open("text.txt","r")
print("file is\n",file.read())
file.close()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
file is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
a=[1,2,3]
b=[3,2,4]
np.equal(a,b)

array([False,  True, False])

In [44]:
a=np.random.randint(9,size=(4,4))
print(a)
a[0,-1]=a[-1,0]
print("\nafter swapp\n\n",a)

[[7 4 5 2]
 [8 7 1 1]
 [6 0 7 1]
 [2 6 4 8]]

after swapp

 [[7 4 5 2]
 [8 7 1 1]
 [6 0 7 1]
 [2 6 4 8]]


In [50]:
a=[1,2,3,4]
b=[5,4,6,7]
c=np.multiply(a,b)
print("a =",a)
print("b =",b)
print("a*b =",c)

a = [1, 2, 3, 4]
b = [5, 4, 6, 7]
a*b = [ 5  8 18 28]
