In [4]:
import numpy as np
rows=int(input("enter no. of rows"))
col=int(input("enetr no. of colums"))
print("enter matrix1 elements")
elements1= list(map(int, input().split()))
print("enter matrix2 elements")
elements2=list(map(int, input().split()))
matrix1=np.array(elements1).reshape(rows,col)
matrix2=np.array(elements2).reshape(rows,col)
print("matrix1 \n",matrix1)
print("matrix2 \n",matrix2)
print("dot product \n",np.dot(matrix1,matrix2))
print("transpose \n",np.transpose(matrix1))
print("trace \n",np.trace(matrix1))
print("rank \n",np.linalg.matrix_rank(matrix1))
print("determinant \n",np.linalg.det(matrix1))
print("inverse \n",np.linalg.inv(matrix1))
w, v = np.linalg.eig(matrix1)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)


enter no. of rows2
enetr no. of colums2
enter matrix1 elements
1 2 3 4
enter matrix2 elements
3 2 1 5
matrix1 
 [[1 2]
 [3 4]]
matrix2 
 [[3 2]
 [1 5]]
dot product 
 [[ 5 12]
 [13 26]]
transpose 
 [[1 3]
 [2 4]]
trace 
 5
rank 
 2
determinant 
 -2.0000000000000004
inverse 
 [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
